services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"
      - "9325:9325"

  api-svc:
    build:
      context: .
      dockerfile: api-svc/Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - SQS_ENDPOINT_URL=http://elasticmq:9324
      - SQS_QUEUE_URL=http://elasticmq:9324/000000000000/transfers
      - DYNAMODB_ACCOUNTS_TABLE=accounts
      - DYNAMODB_TRANSACTIONS_TABLE=transactions
      - PORT=8080
    depends_on:
      - dynamodb-local
      - elasticmq

  worker-svc:
    build:
      context: .
      dockerfile: worker-svc/Dockerfile
    restart: on-failure
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - SQS_ENDPOINT_URL=http://elasticmq:9324
      - SQS_QUEUE_URL=http://elasticmq:9324/000000000000/transfers
      - DYNAMODB_ACCOUNTS_TABLE=accounts
      - DYNAMODB_TRANSACTIONS_TABLE=transactions
    depends_on:
      - dynamodb-local
      - elasticmq
